In [ ]:
import pandas as pd
from pyarrow import csv
from datetime import datetime, timedelta
import os.path
filename = "/content/sample_data/201901.csv"

In [ ]:
li = []
frame = pd.DataFrame()
column_names = ['date', 'time', 'Region', 'Sub_Region', 'Customer_number', 'Contract', 'Contract_Power', 'Supply_type', 'High-Low', 'Active_Energy', 'Lagging_Reactive_Energy ', 'Leading_Reactive_Energy']
    #날짜	시간  시/도	읍_면_동   고객번호	계약종별	계약전력	공급방식	고저압구분	유효전력량	지상무효전력량	진상무효전력량

In [ ]:
try:
    df = csv.read_csv(filename, read_options=csv.ReadOptions(encoding='CP949', skip_rows=1, column_names=column_names)).to_pandas()
    li.append(df)
except:
    print("D")

frame = pd.concat(li, axis=0, ignore_index=True)    # 합치기

frame = frame[['date', 'time', 'Customer_number', 'Contract', 'Contract_Power', 'Active_Energy', 'Region', 'Sub_Region']]

In [ ]:
li

[            date  time Region Sub_Region Customer_number   Contract  \
 0       20190101  1000    경기도     BB001동      b72c577b37  심야전력(을)II
 1       20190101  1015    경기도     BB001동      b72c577b37  심야전력(을)II
 2       20190101  1030    경기도     BB001동      b72c577b37  심야전력(을)II
 3       20190101   815    경기도     BB001동      b72c577b37  심야전력(을)II
 4       20190101   830    경기도     BB001동      b72c577b37  심야전력(을)II
 ...          ...   ...    ...        ...             ...        ...
 680492  20190131  2230    경기도     BB004동      aaac041cbe     가로등(을)
 680493  20190131  2245    경기도     BB004동      aaac041cbe     가로등(을)
 680494  20190131  2315    경기도     BB004동      aaac041cbe     가로등(을)
 680495  20190131  2130    경기도     BB004동      aaac041cbe     가로등(을)
 680496  20190131  2300    경기도     BB004동      aaac041cbe     가로등(을)

         Contract_Power     Supply_type High-Low  Active_Energy  \
 0                  750  삼상4선(22.9kV-y)       고압           0.58
 1                  750  삼상4선(22.9kV-y)       고압           0.54
 2                  750  삼상4선(22.9kV-y)       고압           0.54
 3                  750  삼상4선(22.9kV-y)       고압           0.54
 4                  750  삼상4선(22.9kV-y)       고압           0.54
 ...                ...             ...      ...            ...
 680492               5  삼상4선(22.9kV-y)       고압           0.83
 680493               5  삼상4선(22.9kV-y)       고압           0.83
 680494               5  삼상4선(22.9kV-y)       고압           0.82
 680495               5  삼상4선(22.9kV-y)       고압           0.83
 680496               5  삼상4선(22.9kV-y)       고압           0.83

         Lagging_Reactive_Energy   Leading_Reactive_Energy
 0                           0.18                     0.00
 1                           0.18                     0.00
 2                           0.14                     0.00
 3                           0.18                     0.00
 4                           0.14                     0.00
 ...                          ...                      ...
 680492                      0.00                     0.11
 680493                      0.00                     0.11
 680494                      0.00                     0.11
 680495                      0.00                     0.11
 680496                      0.00                     0.11

 [680497 rows x 12 columns]]

In [ ]:
frame

,date,time,Customer_number,Contract,Contract_Power,Active_Energy,Region,Sub_Region
0,20190101,1000,b72c577b37,심야전력(을)II,750,0.58,경기도,BB001동
1,20190101,1015,b72c577b37,심야전력(을)II,750,0.54,경기도,BB001동
2,20190101,1030,b72c577b37,심야전력(을)II,750,0.54,경기도,BB001동
3,20190101,815,b72c577b37,심야전력(을)II,750,0.54,경기도,BB001동
4,20190101,830,b72c577b37,심야전력(을)II,750,0.54,경기도,BB001동
...,...,...,...,...,...,...,...,...
680492,20190131,2230,aaac041cbe,가로등(을),5,0.83,경기도,BB004동
680493,20190131,2245,aaac041cbe,가로등(을),5,0.83,경기도,BB004동
680494,20190131,2315,aaac041cbe,가로등(을),5,0.82,경기도,BB004동
680495,20190131,2130,aaac041cbe,가로등(을),5,0.83,경기도,BB004동
680496,20190131,2300,aaac041cbe,가로등(을),5,0.83,경기도,BB004동

In [ ]:
column_names

['date',
 'time',
 'Region',
 'Sub_Region',
 'Customer_number',
 'Contract',
 'Contract_Power',
 'Supply_type',
 'High-Low',
 'Active_Energy',
 'Lagging_Reactive_Energy ',
 'Leading_Reactive_Energy']

In [ ]:
frame = pd.concat(li, axis=0, ignore_index=True)    # 합치기

In [ ]:
frame

,date,time,Region,Sub_Region,Customer_number,Contract,Contract_Power,Supply_type,High-Low,Active_Energy,Lagging_Reactive_Energy,Leading_Reactive_Energy
0,20190101,1000,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.58,0.18,0.00
1,20190101,1015,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.18,0.00
2,20190101,1030,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.14,0.00
3,20190101,815,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.18,0.00
4,20190101,830,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.14,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
680492,20190131,2230,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11
680493,20190131,2245,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11
680494,20190131,2315,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.82,0.00,0.11
680495,20190131,2130,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11
680496,20190131,2300,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11

In [ ]:
def convert(row):
        try:
            time = str(row["time"]) if str(row["time"]) != "2400" else "0000"
            x = str(row["date"]) + " " + time
            return datetime.strptime(x, '%Y%m%d %H%M')
        except:
            print(x)

In [ ]:
frame["datetime"] = frame.apply(lambda x: convert(x), axis=1)

In [ ]:
frame

,date,time,Region,Sub_Region,Customer_number,Contract,Contract_Power,Supply_type,High-Low,Active_Energy,Lagging_Reactive_Energy,Leading_Reactive_Energy,datetime
0,20190101,1000,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.58,0.18,0.00,2019-01-01 10:00:00
1,20190101,1015,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.18,0.00,2019-01-01 10:15:00
2,20190101,1030,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.14,0.00,2019-01-01 10:30:00
3,20190101,815,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.18,0.00,2019-01-01 08:15:00
4,20190101,830,경기도,BB001동,b72c577b37,심야전력(을)II,750,삼상4선(22.9kV-y),고압,0.54,0.14,0.00,2019-01-01 08:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
680492,20190131,2230,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11,2019-01-31 22:30:00
680493,20190131,2245,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11,2019-01-31 22:45:00
680494,20190131,2315,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.82,0.00,0.11,2019-01-31 23:15:00
680495,20190131,2130,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11,2019-01-31 21:30:00
680496,20190131,2300,경기도,BB004동,aaac041cbe,가로등(을),5,삼상4선(22.9kV-y),고압,0.83,0.00,0.11,2019-01-31 23:00:00

In [ ]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 680497 entries, 0 to 680496
Data columns (total 13 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   date                      680497 non-null  int64
 1   time                      680497 non-null  int64
 2   Region                    680497 non-null  object
 3   Sub_Region                680497 non-null  object
 4   Customer_number           680497 non-null  object
 5   Contract                  680497 non-null  object
 6   Contract_Power            680497 non-null  int64
 7   Supply_type               680497 non-null  object
 8   High-Low                  680497 non-null  object
 9   Active_Energy             680497 non-null  float64
 10  Lagging_Reactive_Energy   680497 non-null  float64
 11  Leading_Reactive_Energy   680497 non-null  float64
 12  datetime                  680497 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(3), object(6)
memory usage: 67.5+ MB